name: "Cachix build"
on:
  push:
    branches-ignore:
      - "renovate/**"
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**/LICENSE"
      - "flake.lock"
      - "packages/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".markdownlint**"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**/LICENSE"
      - "flake.lock"
      - "packages/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".markdownlint**"
  workflow_dispatch:
jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: freesmlauncher
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix-build | cachix push freesmlauncher
      - run: |
          nix develop
          echo "OK"
