name: "Cachix fallback"
run-name: "Building app for cachix cache"
on:
  check_suite:
    types: [completed]
  workflow_dispatch:
jobs:
  debug-info:
    runs-on: ubuntu-latest
    steps:
      - name: Show check suite event data
        run: echo "${{ toJson(github.event) }}"
  build-and-cache:
    if: ${{ github.event.check_suite.conclusion == 'failure' && contains(github.event.check_suite.check_runs.*, 'Evaluate flake.nix') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: freesmlauncher
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix-build
      - run: nix-shell --run "echo OK"
