name: "Cachix build"
on:
  check_run:
    types:
      - completed
jobs:
  build-and-cache:
    if: ${{ github.event.check_run.name == 'Evaluate flake.nix' && github.event.check_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: freesmlauncher
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix-build | cachix push freesmlauncher
      - run: nix-shell --run "echo OK"
